base_llm: meta-llama/Llama-3.1-8B-Instruct
base_model: null
attachment_token: <|reserved_special_token_0|>
tokenizer_type: llama
token_size: 4096

loaders:
  - loader_type: raw-image
    modality_type: image

modalities:
  - model_type: meditron_biomedclip
    clip_name: michel-ducartier/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224
    hidden_size: 4096
    trust_remote_code: true

training_mode: ALIGNMENT

datasets:
  # Non formatted dataset
  # ---------------------
  - packed_path: $STORAGE_ROOT/llava_pretrain_cleaned
  - packed_path: $STORAGE_ROOT/pixmo_anything
  - packed_path: $STORAGE_ROOT/pixmo_cap
  - packed_path: $STORAGE_ROOT/medtrinity_conversations_1_formatted_alignment/

  
training_args:
  output_dir: $MODEL_ROOT/freeze/single_clip/MultiMeditron-Llama-8B-Alignment-BiomedCLIP
  dataloader_num_workers: 16  # > 0 not supported for IterableDataset, cf. https://github.com/huggingface/datasets/issues/5984
  dataloader_prefetch_factor: 4
  remove_unused_columns: false
  ddp_find_unused_parameters: false # Test to reduce memory
  learning_rate: 1.0e-4
  bf16: true
  per_device_train_batch_size: 4  # note that training_args.n_gpu and training_args.train_batch_size show faulty values
                                  # with deepspeed -> use deepspeed_plugin instead (besides training_args.distributed_state.num_processes == WORLD_SIZE)
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: true
  save_strategy: epoch
  # save_steps: 0.25
  max_grad_norm: 1.0
  run_name: MultiMeditron-Llama-8B-BiomedCLIP-Alignment     # Set the name for the run
  deepspeed: $WORKING_DIR/config/deepspeed.json
  accelerator_config:
    dispatch_batches: false
  lr_scheduler_type: "cosine_with_min_lr"
  lr_scheduler_kwargs:
    min_lr: 3.0e-5
  report_to: wandb
  logging_steps: 1
  weight_decay: 0.01

